import { execSync } from "child_process";
import { existsSync, writeFileSync, unlinkSync } from "fs";


type LogFn = (message: string) => Promise<void>;

export interface DeployConfig {
  deploymentId: string;
  serviceId: string;
  subdomain: string;
  runtime: "node" | "python" | "go" | "static";
  envVars: Record<string, string>;
}

const PORT_RANGE_START = 4000;
const PORT_RANGE_END = 4999;

const HOLONET_DOMAIN = process.env.HOLONET_DOMAIN ?? "hitanshu.xyz";

const RUNTIME_PORTS: Record<string, number> = {
  node: 3000,
  python: 8000,
  go: 8080,
  static: 80,
};

function exec(cmd: string): string {
  return execSync(cmd, {
    encoding: "utf-8",
    stdio: ["pipe", "pipe", "pipe"],
    timeout: 60_000,
  }).trim();
}

function execSafe(cmd: string): string | null {
  try {
    return exec(cmd);
  } catch {
    return null;
  }
}

function getUsedPorts(): Set<number> {
  const used = new Set<number>();

  try {
    const output = exec(
      `docker ps --format '{{.Ports}}' | grep -oP '0\\.0\\.0\\.0:\\K[0-9]+' || true`
    );
    for (const line of output.split("\n")) {
      const port = parseInt(line.trim(), 10);
      if (!isNaN(port)) used.add(port);
    }
  } catch {
  }

  return used;
}

function findAvailablePort(): number {
  const usedPorts = getUsedPorts();

  for (let port = PORT_RANGE_START; port <= PORT_RANGE_END; port++) {
    if (!usedPorts.has(port)) return port;
  }

  throw new Error(
    `No available ports in range ${PORT_RANGE_START}-${PORT_RANGE_END}. Too many deployed services.`
  );
}


const CONTAINER_PREFIX = "holonet-";

function containerName(subdomain: string): string {
  return `${CONTAINER_PREFIX}${subdomain}`;
}

export async function stopContainer(
  subdomain: string,
  log?: LogFn
): Promise<void> {
  const name = containerName(subdomain);

  const existing = execSafe(`docker inspect --format '{{.State.Status}}' ${name}`);
  if (!existing) return;

  await log?.(`Stopping existing container: ${name}`);
  execSafe(`docker stop ${name}`);
  execSafe(`docker rm -f ${name}`);
  await log?.(`Removed container: ${name}`);
}

export async function deployContainer(
  config: DeployConfig,
  imageName: string,
  log: LogFn
): Promise<string> {
  const { subdomain, runtime, envVars } = config;
  const name = containerName(subdomain);

  await stopContainer(subdomain, log);

  const hostPort = findAvailablePort();
  const containerPort = RUNTIME_PORTS[runtime] ?? 3000;
  await log(`Allocated port ${hostPort} → container:${containerPort}`);
  const envFlags = Object.entries(envVars)
    .map(([key, value]) => `-e ${key}="${value}"`)
    .join(" ");

  const dockerCmd = [
    "docker run -d",
    `--name ${name}`,
    `-p 127.0.0.1:${hostPort}:${containerPort}`,
    "--restart unless-stopped",
    `--memory=512m`,
    `--cpus=0.5`,
    envFlags,
    imageName,
  ]
    .filter(Boolean)
    .join(" ");

  await log(`Starting container: ${name}`);
  const containerId = exec(dockerCmd);
  await log(`Container started: ${containerId.slice(0, 12)}`);

  await log(`Waiting for container health check...`);
  await waitForContainer(name, log);

  await configureNginx(subdomain, hostPort, log);

  const deployUrl = `https://${subdomain}.${HOLONET_DOMAIN}`;
  await log(`🚀 Live at ${deployUrl}`);

  return deployUrl;
}

 
async function waitForContainer(
  name: string,
  log: LogFn,
  maxAttempts = 15,
  intervalMs = 2000
): Promise<void> {
  for (let i = 0; i < maxAttempts; i++) {
    const status = execSafe(
      `docker inspect --format '{{.State.Status}}' ${name}`
    );

    if (status === "running") {
      await log(`Container is running`);
      return;
    }

    if (status === "exited" || status === "dead") {
      const logs = execSafe(`docker logs --tail 30 ${name}`) ?? "No logs available";
      throw new Error(
        `Container exited unexpectedly (status: ${status}).\nLast logs:\n${logs}`
      );
    }

    await new Promise((resolve) => setTimeout(resolve, intervalMs));
  }

  throw new Error(`Container ${name} did not become healthy within ${maxAttempts * intervalMs / 1000}s`);
}

const NGINX_SITES_DIR = "/etc/nginx/sites-available";
const NGINX_ENABLED_DIR = "/etc/nginx/sites-enabled";

async function configureNginx(
  subdomain: string,
  port: number,
  log: LogFn
): Promise<void> {
  const confName = `holonet-${subdomain}`;
  const confPath = `${NGINX_SITES_DIR}/${confName}`;
  const enabledPath = `${NGINX_ENABLED_DIR}/${confName}`;

  const config = `
# Auto-generated by Holonet Deployer — do not edit manually
server {
    listen 80;
    server_name ${subdomain}.${HOLONET_DOMAIN};

    location / {
        proxy_pass http://127.0.0.1:${port};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;

        # Timeouts for long-running requests
        proxy_connect_timeout 60s;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }

    # Health check endpoint for Holonet
    location /_holonet/health {
        return 200 '{"status":"ok","subdomain":"${subdomain}","port":${port}}';
        add_header Content-Type application/json;
    }
}
`.trim();

  await log(`Configuring Nginx for ${subdomain}.${HOLONET_DOMAIN} → port ${port}`);

  writeFileSync(`/tmp/nginx-${confName}`, config, "utf-8");
  exec(`sudo cp /tmp/nginx-${confName} ${confPath}`);
  exec(`sudo ln -sf ${confPath} ${enabledPath}`);

  exec(`sudo nginx -t`);
  exec(`sudo systemctl reload nginx`);

  await log(`Nginx configured and reloaded`);
}

export async function removeNginxConfig(subdomain: string): Promise<void> {
  const confName = `holonet-${subdomain}`;
  const confPath = `${NGINX_SITES_DIR}/${confName}`;
  const enabledPath = `${NGINX_ENABLED_DIR}/${confName}`;

  try {
    if (existsSync(enabledPath)) unlinkSync(enabledPath);
  } catch {}

  execSafe(`sudo rm -f ${confPath}`);
  execSafe(`sudo systemctl reload nginx`);
}

export function getContainerInfo(
  subdomain: string
): { running: boolean; port: number | null; containerId: string | null } {
  const name = containerName(subdomain);

  const status = execSafe(`docker inspect --format '{{.State.Status}}' ${name}`);
  if (!status || status !== "running") {
    return { running: false, port: null, containerId: null };
  }

  const containerId = execSafe(
    `docker inspect --format '{{.Id}}' ${name}`
  );

  const portMapping = execSafe(
    `docker port ${name} | head -1 | grep -oP '\\d+$'`
  );
  const port = portMapping ? parseInt(portMapping, 10) : null;

  return {
    running: true,
    port,
    containerId: containerId?.slice(0, 12) ?? null,
  };
}
